name: quizPlugin
author: vekotov
website: https://github.com/vekotov/minecraft_testing/
version: '0.03'
main: vekotov.ru.quizPlugin.quizPlugin

commands:
  answer:
    description: Ответить на вопрос.
    usage: /<command> [answer]
  startgame:
    description: Начинает игру
    usage: /<command>